# .gitlab-ci.yml

stages:
  - build
  
# 1. Linux 에서 cibuildwheel 로 빌드
build_wheels_linux:
  stage: build
  image: python:3.12
  tags:
    - linux
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CIBW_BUILD: "cp39-* cp311-* cp312-*"
    CIBW_ARCHS_LINUX: "x86_64"
  before_script:
    - apt-get update -qq && apt-get install -qq -y docker.io
    - pip install --upgrade pip
    - pip install cibuildwheel build wheel setuptools
  script:
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl

# 2. Windows 런너(태그가 'windows' 로 지정된 Runner)에서 빌드
build_wheels_windows:
  stage: build
  image: mcr.microsoft.com/windows/servercore:ltsc2019
  tags:
    - windows
  before_script:
    - python -m pip install --upgrade pip
    - pip install cibuildwheel build wheel setuptools
  script:
    - cibuildwheel --platform windows --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week