# .gitlab-ci.yml

stages:
  - build

# 1. Linux 에서 cibuildwheel 로 빌드
build_wheels_linux:
  stage: build
  image: python:3.12
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # cibuildwheel 환경 변수
    CIBW_BUILD: "cp39-* cp311-* cp312-*"
    CIBW_SKIP: "*-musllinux*"
  script:
    - pip install --upgrade pip
    - pip install cibuildwheel==2.* build wheel setuptools
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week

# 2. Windows 런너(태그가 'windows' 로 지정된 Runner)에서 빌드
build_wheels_windows:
  stage: build
  tags:
    - windows
  image: mcr.microsoft.com/windows/servercore:ltsc2019  # 또는 Windows 런너가 지원하는 이미지
  variables:
    CIBW_BUILD: "cp39-* cp311-* cp312-*"
    CIBW_SKIP: "*win32*"
  before_script:
    - python -m pip install --upgrade pip
    - pip install cibuildwheel==2.* build wheel setuptools
  script:
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week

# 3. macOS 런너(태그가 'macos' 로 지정된 Runner)에서 빌드
build_wheels_macos:
  stage: build
  tags:
    - macos
  image: python:3.12  # macOS 전용 Runner 에 맞게 조정
  before_script:
    - python3 -m pip install --upgrade pip
    - pip3 install cibuildwheel==2.* build wheel setuptools
  script:
    - cibuildwheel --platform macos --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week

# Optional: 태그 v* 가 붙은 push 또는 수동 트리거
# 기본적으로 모든 브랜치 푸시에 대해 실행되지만,
# GitHub Actions 와 유사하게 태그 푸시에만 실행하고 싶다면 아래처럼 제한할 수 있습니다.
# 
# only:
#   refs:
#     - /^v\d+\.\d+\.\d+$/  # v1.2.3 형식의 태그에만 실행
#   variables:
#     - $CI_PIPELINE_SOURCE == "push"
#
# + 수동 트리거 추가:
#   when: manual